CREATE TABLE reporting.saved_erp_reports (
  id uuid PRIMARY KEY,
  owner_account_id uuid NOT NULL REFERENCES identity.user_accounts(id),
  scope varchar(30) NOT NULL CHECK (scope IN ('procurement','warehouse','sales','logistics')),
  name varchar(100) NOT NULL CHECK (length(trim(name)) > 0),
  configuration jsonb NOT NULL CHECK (jsonb_typeof(configuration) = 'object' AND configuration ? 'definitionKey' AND configuration->>'definitionKey' LIKE scope || '.%'),
  request_hash char(64) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX saved_erp_reports_owner_idx ON reporting.saved_erp_reports(owner_account_id,scope,created_at DESC,id);
INSERT INTO reporting.report_definitions (id,definition_key,name,description,implementation_key,available_formats,filter_schema) VALUES
(gen_random_uuid(),'procurement.order-comparison','Purchase order comparison','One row per ordered product. Compare ordered, received and invoiced quantities. Dates use order creation.','procurement.order-comparison.v1',ARRAY['csv','xlsx','pdf']::varchar[],'{"type":"object","additionalProperties":false,"properties":{"search":{"type":"string","maxLength":120},"dateFrom":{"type":"string","format":"date"},"dateTo":{"type":"string","format":"date"}},"required":["dateFrom","dateTo"]}'::jsonb),
(gen_random_uuid(),'procurement.supplier-claims','Supplier claims','Recorded supplier claims with quantity, type and current status. Dates use claim creation.','procurement.supplier-claims.v1',ARRAY['csv','xlsx','pdf']::varchar[],'{"type":"object","additionalProperties":false,"properties":{"search":{"type":"string","maxLength":120},"dateFrom":{"type":"string","format":"date"},"dateTo":{"type":"string","format":"date"}},"required":["dateFrom","dateTo"]}'::jsonb),
(gen_random_uuid(),'warehouse.stock-balances','Stock and valuation','Current recorded stock by warehouse and product, including active reservations and weighted-average BGN value. This is not a historical stock snapshot.','warehouse.stock-balances.v1',ARRAY['csv','xlsx','pdf']::varchar[],'{"type":"object","additionalProperties":false,"properties":{"search":{"type":"string","maxLength":120}}}'::jsonb),
(gen_random_uuid(),'warehouse.movements','Stock movements','Traceable inventory transactions by posting date. Quantities are recorded movement amounts; the movement type identifies the direction.','warehouse.movements.v1',ARRAY['csv','xlsx','pdf']::varchar[],'{"type":"object","additionalProperties":false,"properties":{"search":{"type":"string","maxLength":120},"dateFrom":{"type":"string","format":"date"},"dateTo":{"type":"string","format":"date"}},"required":["dateFrom","dateTo"]}'::jsonb),
(gen_random_uuid(),'warehouse.replenishment','Replenishment','Current minimum-stock settings and purchase recommendations. Includes configured stock policies only; recommended quantity is target less available, never below zero.','warehouse.replenishment.v1',ARRAY['csv','xlsx','pdf']::varchar[],'{"type":"object","additionalProperties":false,"properties":{"search":{"type":"string","maxLength":120}}}'::jsonb),
(gen_random_uuid(),'sales.quotation-register','Quotations and orders','One row per quotation with its confirmed order and current stage. Totals remain in the original currency, including VAT. Dates use quotation creation.','sales.quotation-register.v1',ARRAY['csv','xlsx','pdf']::varchar[],'{"type":"object","additionalProperties":false,"properties":{"search":{"type":"string","maxLength":120},"dateFrom":{"type":"string","format":"date"},"dateTo":{"type":"string","format":"date"}},"required":["dateFrom","dateTo"]}'::jsonb),
(gen_random_uuid(),'sales.shipment-register','Shipments','Completed shipments with their sales order and prepared invoice draft. Dates use shipment completion. Invoice drafts are not official invoices.','sales.shipment-register.v1',ARRAY['csv','xlsx','pdf']::varchar[],'{"type":"object","additionalProperties":false,"properties":{"search":{"type":"string","maxLength":120},"dateFrom":{"type":"string","format":"date"},"dateTo":{"type":"string","format":"date"}},"required":["dateFrom","dateTo"]}'::jsonb),
(gen_random_uuid(),'logistics.deliveries','Deliveries','Planned and completed deliveries by scheduled start date. Includes cancellations and exceptions; courier records do not imply a live carrier booking.','logistics.deliveries.v1',ARRAY['csv','xlsx','pdf']::varchar[],'{"type":"object","additionalProperties":false,"properties":{"search":{"type":"string","maxLength":120},"dateFrom":{"type":"string","format":"date"},"dateTo":{"type":"string","format":"date"}},"required":["dateFrom","dateTo"]}'::jsonb),
(gen_random_uuid(),'logistics.returns','Returns and repairs','One row per returned product, linked to its shipment, receiving warehouse and Service request where applicable. Dates use return registration.','logistics.returns.v1',ARRAY['csv','xlsx','pdf']::varchar[],'{"type":"object","additionalProperties":false,"properties":{"search":{"type":"string","maxLength":120},"dateFrom":{"type":"string","format":"date"},"dateTo":{"type":"string","format":"date"}},"required":["dateFrom","dateTo"]}'::jsonb),
(gen_random_uuid(),'logistics.routes','Route plans','Route schedules, assigned employees and stop counts by route date. Cancelled plans remain visible.','logistics.routes.v1',ARRAY['csv','xlsx','pdf']::varchar[],'{"type":"object","additionalProperties":false,"properties":{"search":{"type":"string","maxLength":120},"dateFrom":{"type":"string","format":"date"},"dateTo":{"type":"string","format":"date"}},"required":["dateFrom","dateTo"]}'::jsonb);
